package com.ram.synchronization;

class Brackets{
	
	synchronized public static void generate(String threadCode) {

		for(int i=0; i<=10; i++) {
			if(i<=5) {
				System.out.print("[");
			}else {
				System.out.print("]");
			}
		}
		System.out.println("generated by thread "+ threadCode);
	}
}
public class AppStatic {

	public static void main(String[] args) {

		new Thread(new Runnable() {
			
			@Override
			public void run() {
				for(int i=1; i<=5; i++) {
					Brackets.generate("thread 1");
				}
			}
		}).start();
		
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				for(int i=1; i<=5; i++) {
					Brackets.generate("thread 2");
				}
			}
		}).start();
		
	}

}
